### ISSUE TITLE
Make a 0.4.1 release

### ISSUE THREAD

**Issue by Freso** [JoeLametta/whipper#104]
The Git submodules were removed in git but were still required at the release of 0.4.0. However, GitHub doesn't include submodules when it's packaging up releases, so people downloading the release will be unable to make it work (since the downloaded archive is not a git archive, you can't run git commits (e.g., `git submodule init`) in/on it). A patch version bump seems appropriate for this—and would allow me (and other packagers) to package a "stable" `whipper` without going through hoops to pull in the git submodules manually.

**Comment by ArchangeGabriel** [comment]
Thanks for having done this quickly @JoeLametta!

**Comment by JoeLametta** [comment]
Done!

[v0.4.1](https://github.com/JoeLametta/whipper/releases/tag/v0.4.1)
