### ISSUE TITLE
0.4.1 Release created but version number in code not bumped

### ISSUE THREAD

**Issue by mruszczyk** [JoeLametta/whipper#105]
With the release of 0.4.1 the version number was not bumped in code which causes the site-packages to still be whipper-0.4.0-py2.7.egg-info.

**Comment by ArchangeGabriel** [comment]
You also have to redo the tag and GitHub release.

**Comment by JoeLametta** [comment]
> You also have to redo the tag and GitHub release.

Tagged a new release instead ([0.4.2](https://github.com/JoeLametta/whipper/releases/tag/v0.4.2)).
