### ISSUE TITLE
additional tag creation

### ISSUE THREAD

**Issue by gthieleb** [JoeLametta/whipper#108]
After ripping I want whipper to add additional tags from musicbrainz to the file. For some reason I want the barcode tag to be included. Currently a flac file is created with this tag set:

	$ metaflac --list file.flac

	METADATA block #0
	  type: 0 (STREAMINFO)
	  is last: false
	  length: 34
	  minimum blocksize: 4608 samples
	  maximum blocksize: 4608 samples
	  minimum framesize: 14 bytes
	  maximum framesize: 15421 bytes
	  sample_rate: 44100 Hz
	  channels: 2
	  bits-per-sample: 16
	  total samples: 8024436
	  MD5 signature: 543475f101ff45c6443068ecf259b91a
	METADATA block #1
	  type: 4 (VORBIS_COMMENT)
	  is last: true
	  length: 460
	  vendor string: reference libFLAC 1.3.0 20130526
	  comments: 11
	    comment[0]: ALBUMARTIST=****
	    comment[1]: ARTIST=K********
	    comment[2]: TITLE=Moving
	    comment[3]: ALBUM=T**************
	    comment[4]: TRACKNUMBER=1
	    comment[5]: DATE=1994-09-12
	    comment[6]: MUSICBRAINZ_TRACKID=5e530ec8-93f1-45c9-96d2-e4d99f0ecee6
	    comment[7]: MUSICBRAINZ_ARTISTID=4b585938-f271-45e2-b19a-91c634b5e396
	    comment[8]: MUSICBRAINZ_ALBUMID=3284a453-7f3c-36f7-a46c-42ab0310e51f
	    comment[9]: MUSICBRAINZ_ALBUMARTISTID=4b585938-f271-45e2-b19a-91c634b5e396
	    comment[10]: MUSICBRAINZ_DISCID=3PxaiCNYxU_173eM7lR9rVCl8qo-

Where do I find the list of valid tags (valid in context of whipper) in the code?

**Comment by JoeLametta** [comment]
> Where do I find the list of valid tags (valid in context of whipper) in the code?

[morituri/common/program.py](https://github.com/JoeLametta/whipper/blob/master/morituri/common/program.py)

Whipper uses the [Musicbrainz NGS python bindings](python-musicbrainzngs.readthedocs.io) to get metadata from MusicBrainz.

**Comment by ArchangeGabriel** [comment]
You can use other tools for that too. Look at Exfalso (part of [QuodLibet](http://quodlibet.readthedocs.org/) for instance).

For whipper, we have to all agree on the direction we should go regarding tags, but current consensus is we don’t want to add more and more things while they are other great tools out there for such purposes, but also that this discussion should be postponed toward 1.0 release.
