### ISSUE TITLE
'whipper drive list' returns a suggestion to run 'rip offset find'

### ISSUE THREAD

**Issue by axelsimon** [JoeLametta/whipper#112]
Hi,
Running `whipper drive list` returns a suggestion to run `rip offset find` instead of `whipper offset find`, causing it to fail if one follows the suggestion.

There are probably more in the code (after all, it's a fork, it's bound to happen) but I thought it might be worth mentioning :)

Hope this helps.

**Comment by JoeLametta** [comment]
> There are probably more in the code (after all, it's a fork, it's bound to happen) but I thought it might be worth mentioning :)

I'll check if there are other similar issues and fix them.

> Hope this helps.

Sure, thanks for the bug report!

**Comment by JoeLametta** [comment]
I've checked and, apart from lots of strings in comments, I've found only two occurrences which I'm going to fix now.

**Comment by JoeLametta** [comment]
Done!
