### ISSUE TITLE
Whipper 0.4.0 won't run on Debian Stretch (testing)

### ISSUE THREAD

**Issue by axelsimon** [JoeLametta/whipper#113]
Hi,
First of all, thanks for this great ripper :smiley:
I might be wrong here or have missed something, in which case sorry in advance, but I can't seem to get whipper to work on Debian Stretch (testing).

It's likely due to the fact `gstreamer0.10-*` packages are no longer available, only `gstreamer1.0-*` packages are suggested by an `apt search`, same thing for `python-gst-1.0`, no `python-gst0.10` to be found in Stretch repos, as far as I can tell.

whipper throws a `ImportError: No module named gst` when trying to get offsets or rip a disc.

Am I missing something?

thanks

**Comment by JoeLametta** [comment]
> Hi,
> First of all, thanks for this great ripper 😃

👍 

> Am I missing something?

No, you're right and that's the reason morituri has been dropped from stretch and won't be available anymore in future releases.

We've planned to drop GStreamer's dependency long ago and that should happen very soon™ (as stated in the [README](https://github.com/JoeLametta/whipper#required-dependencies).
For more information regarding this one, I suggest you to follow issue #29 ("Remove gstreamer dependency").

;)

**Comment by axelsimon** [comment]
Understood, thanks for the explanation.
I saw (and chuckled) at the README's mention of dropping GStreamer real soon™, i'll follow the issue then. :)

**Comment by axelsimon** [comment]
In case this can help out others, I got it working on Debian Stretch (9.0) testing.

The dependencies game gets a bit more complicated than mentioned on the README, so I'll describe what I needed here.
Get all the stated dependencies:
`sudo aptitude install libgstreamer0.10-0 cdparanoia cdrdao python-gobject-2 python-musicbrainzngs python-mutagen python-setuptools python-cddb libsndfile1-dev flac sox`
`libgstream0.10-0` gets pulled from the stable Debian repo, so make sure you have `deb http://http.debian.net/debian/ stable main contrib non-free` or something similar in your /etc/apt/sources.list.
At some point, I think flac-dev, libsndfile1 etc. get pulled in. Apt should take care of that automatically for you.

However, we aren't done, as `pycdio` is not packaged in Debian, so no `apt install`ing that one. We will have to install it with `pip`. Which in turn requires more dev packages and swig. So:
`sudo apt install swig libcdio-paranoia-dev libiso9660-dev`
and then `sudo pip install pycdio`
If you don't have pip installed, please follow a guide elsewhere, it's beyond the scope here.

Once you have all these dependencies installed, you can go back to the README's install procedure (cd src, make, etc.).

Hope this helps.

**Comment by MerlijnWajer** [comment]
gstreamer is no longer a dependency of whipper. You do not need libgstreamer-0.10-0.

**Comment by axelsimon** [comment]
Ahh well that's even better then. Great.
Also, just realised that these instructions are basically the same as the ones here: https://github.com/JoeLametta/whipper/wiki/Required-Dependencies Oh well.
