### ISSUE TITLE
Loggers

### ISSUE THREAD

**Issue by ArchangeGabriel** [JoeLametta/whipper#117]
morituri starting to be dropped from distributions (because of gstreamer0.10), I think that the loggers should start being named `whipper-<loggername>` instead of `morituri-`. This would be more explicit and understandable for new comers.

I’m posting this here since this is a whipper related issue, but I’m especially targeting @RecursiveForest and @JoeLametta who happen to maintain most (if not all) of the external loggers.

**Comment by IvanDSM** [comment]
Agreed, would clear up any possible future confusion.

**Comment by JoeLametta** [comment]
- [morituri-yamllogger](https://github.com/JoeLametta/morituri-yamllogger) only targets morituri.
- [morituri-eaclogger](https://github.com/JoeLametta/morituri-eaclogger) works both with whipper and morituri.
It can be renamed to `whipper-eaclogger` while updating whipper's README to clarify its compatibility status but this change requires coordination with @RecursiveForest not to break the [whipper-eaclogger-git](https://aur.archlinux.org/packages/whipper-eaclogger-git) package.

I don't remember if @RecursiveForest intends to keep developing [morituri-whatlogger](https://github.com/RecursiveForest/morituri-whatlogger) but being it only compatible with whipper it can be easily renamed without too much thought.

**Comment by ArchangeGabriel** [comment]
Well if @RecursiveForest is OK with that, I can fix [whipper-eaclogger-git](https://aur.archlinux.org/packages/whipper-eaclogger-git) when required.

**Comment by ArchangeGabriel** [comment]
@JoeLametta Before long morituri won’t even be possible to install on any distro, so… Not sure whether it’s worth keeping the old loggers targeting only it.

**Comment by JoeLametta** [comment]
> @JoeLametta Before long morituri won’t even be possible to install on any distro, so… Not sure whether it’s worth keeping the old loggers targeting only it.

Right now it isn't so hard to keep them compatible: what you're saying is right but morituri is still available on Debian Jessie (which will be supported until 2020) and it can probably be installed / compiled on other distros too (CentOS?)...

I think the right time to end morituri support will be as soon as we've got whipper natively packaged by the main distributions.

**Comment by Freso** [comment]
FWIW, any "morituri" loggers will need to be updated since #109 as whipper will no longer pick up loggers installed for morituri.

**Comment by JoeLametta** [comment]
@RecursiveForest Is [morituri-whatlogger](https://github.com/RecursiveForest/morituri-whatlogger) still maintained / useful?

**Comment by JoeLametta** [comment]
All maintained loggers have been updated and moved to the [whipper-team](https://github.com/whipper-team/) organization:

- [whipper-plugin-eaclogger](https://github.com/whipper-team/whipper-plugin-eaclogger)
- [morituri-plugin-eaclogger](https://github.com/whipper-team/morituri-plugin-eaclogger)
- [morituri-plugin-yamllogger](https://github.com/whipper-team/morituri-plugin-yamllogger)

I'll update whipper's README with the updated reference.

P.S.: I think [morituri-whatlogger](https://github.com/RecursiveForest/morituri-whatlogger) won't be developed anymore.
