### ISSUE TITLE
FreeDB metadata not honored

### ISSUE THREAD

**Issue by ubitux** [JoeLametta/whipper#119]
The disk is found on FreeDB but doesn't seem to get the track metadata:

```
☭ whipper cd rip --offset=6 --unknown
Checking device /dev/sr0
eject: CD-ROM tray close command failed: Input/output error
CDDB disc id: fd124612
MusicBrainz disc id 3NcRswJ6LhM352OtBd4O3VoTuZE-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+18+351001+150+24297+41958+69466+89888+106614+120764+138571+155473+182283+206510+221355+258194+269088+282498+300091+313419+332557&tracks=18&id=3NcRswJ6LhM352OtBd4O3VoTuZE-
Disc duration: 01:17:58.013, 18 audio tracks
Error: NotFoundException(ResponseError(),)
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as Siobhán Armstrong  / Lord Gallaway's Delight
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Creating output directory ./unknown/Unknown Artist - 3NcRswJ6LhM352OtBd4O3VoTuZE-
Ripping track 1 of 18: 01. Unknown Artist - Unknown Track 1.flac
```

Note: `cdrdao read-toc` took a very long time with no message displayed about progress or anything, I thought it was stalled.

**Comment by JoeLametta** [comment]
> The disk is found on FreeDB but doesn't seem to get the track metadata:

That's a design choice: whipper only uses high quality metadata for the tagging process (currently whipper's only source is MuscicBrainz). That behavior is documented in the [README](https://github.com/JoeLametta/whipper#required-dependencies) (emphasis mine):

> [python-cddb](http://cddb-py.sourceforge.net/), _for showing **but not using** metadata_ if disc not available in the MusicBrainz DB

---

> Note: `cdrdao read-toc` took a very long time with no message displayed about progress or anything, I thought it was stalled.

Yeah that's how it currently behaves: there's an open issue (#106) which is related to your note.

**Comment by ubitux** [comment]
> That's a design choice: whipper only uses high quality metadata for the tagging process (currently whipper's only source is MuscicBrainz).

So high quality or nothing? Could we at least have an option such as `--fallback-on-lq-tags` or whatever? Because filling them manually is a real PitA, and it's especially annoying when you know the pre-filled tags from freedb need close to zero adjustment...

Now if the low quality risk is really not tolerable, I believe it's better to completely drop the dependency, which is currently only misleading and harmful.

**Comment by MerlijnWajer** [comment]
On 29/01/17 17:53, Clément Bœsch wrote:
>     That's a design choice: whipper only uses high quality metadata for
>     the tagging process (currently whipper's only source is MuscicBrainz).
> 
> So high quality or nothing? Could we at least have an option such as
> |--fallback-on-lq-tags| or whatever? Because filling them manually is a
> real PitA, and it's especially annoying when you know the pre-filled
> tags from freedb need close to zero adjustment...
> 
> Now if the low quality risk is really not tolerable, I believe it's
> better to completely drop the dependency, which is currently only
> misleading and harmful.

The dependency is there for the .log files as well, those usually show a
freedb ID as well.

**Comment by ArchangeGabriel** [comment]
I think dropping the dependency was discussed. If the data from FreeDB are good, then import them into MusicBrainz. ;)

**Comment by ubitux** [comment]
> If the data from FreeDB are good, then import them into MusicBrainz. ;)

I'm fine with that, but as far as I can tell, `whipper` wants me to do that manually.

**Comment by JoeLametta** [comment]
> I think dropping the dependency was discussed. If the data from FreeDB are good, then import them into MusicBrainz. ;)

We'll need to reach a conclusion about that one... also note that [python-cddb](http://cddb-py.sourceforge.net/) is only compatible with Python 2 (I think it can be easily fixed but whipper should avoid embedding custom versions of external dependencies in its repository^).

^ Latest upstream release is from 2003.

**Comment by ubitux** [comment]
6/6 of the CDs I tried yesterday had no entry in MusicBrainz but could be found on FreeDB. So while I understand the need to contribute to MusicBrainz, it makes the encode process way more cumbersome than it should be. I really believe `--unknown` should be replaced with `--allow-freedb-meta` or similar, with a big WARNING display.

Alternatively (or additionally), https://musicbrainz.org/doc/Development/Release_Editor_Seeding could be used to pre-seed MB with FreeDB info to ease the process.

**Comment by ArchangeGabriel** [comment]
@JoeLametta Forking it to port it toward Python 3 shouldn’t be hard, there is a really limited number of LOC.

@ubitux So to be sure I understand it correctly, you would like whipper to provide a link POST’ing FreeDB information into MusicBrainz to ease the process of adding the release? That sounds like a sane feature to have.

**Comment by ubitux** [comment]
> @ubitux So to be sure I understand it correctly, you would like whipper to provide a link POST’ing FreeDB information into MusicBrainz to ease the process of adding the release? That sounds like a sane feature to have.

Yeah, just like the URL that is currently provided (the /cdstub/add thing). Unfortunately, you will obviously only be able to transmit info through GET with a link, which I'm not sure MB accepts. That's do-able with a curl request but that won't allow you manual editing in your browser so you'll have to design some kind of editing interface one way or another, which might be a real pain.

That's just a suggestion, the rationale being that if you impose MusicBrainz, at least make it usable by doing 95% of the work using FreeDB (or another source) if it's available. The current teasing feature "I know the metadata but I don't want you to use it" is too aggressive IMO.

**Comment by Freso** [comment]
I don't know if the release editor allows seeding with GET arguments (@mwiencek?), but I definitely echo the sentiment that somehow doing that (seeding the release editor) is the best approach to this.

Picard's ["Add Release As Cluster" plugin](https://github.com/metabrainz/picard-plugins/blob/master/plugins/addrelease/addrelease.py) does this be creating an HTML form locally with the data and opening that in the browser. This does require an additional click by the user, but might be an approach that can be used if /release/add seeding doesn't work with GET.

**Comment by mwiencek** [comment]
> I don't know if the release editor allows seeding with GET arguments (@mwiencek?)

Only POST at the moment.

**Comment by awsms** [comment]
> 6/6 of the CDs I tried yesterday had no entry in MusicBrainz but could be found on FreeDB. So while I understand the need to contribute to MusicBrainz, it makes the encode process way more cumbersome than it should be.

Same here, this is super-frustrating.

**Comment by vguttmann** [comment]
> > That's a design choice: whipper only uses high quality metadata for the tagging process (currently whipper's only source is MuscicBrainz).
> 
> So high quality or nothing? Could we at least have an option such as `--fallback-on-lq-tags` or whatever? Because filling them manually is a real PitA, and it's especially annoying when you know the pre-filled tags from freedb need close to zero adjustment...
> 
> Now if the low quality risk is really not tolerable, I believe it's better to completely drop the dependency, which is currently only misleading and harmful.

There's no fallback option, but of course there's `--unknown`...
No metadata instead of bad metadata seems like a major oversight to me. Of course there's the possibility of incorrect metadata, but you can always use audio fingerprinting to match it with the metadata if the metadata was incorrect.
