### ISSUE TITLE
Check that whipper deals properly with CD pre-emphasis

### ISSUE THREAD

**Issue by Freso** [JoeLametta/whipper#120]
I'd imagine that morituri already handled this properly and is seems to be a fairly rare occurrance, but still, "better safe than sorry".

http://wiki.hydrogenaud.io/index.php?title=Pre-emphasis
https://web.archive.org/web/20141004045917/http://blowfish.be/eac/Rip/rip12-preemph.html

**Comment by JoeLametta** [comment]
I haven't checked but I think current whipper versions correctly detect the pre-emphasis flag (both in TOC and the subcode) and add it to the generated cue sheet (it's also reported if ripping with the `WHIPPER_DEBUG` environment variable set).  What still needs to be done is including that information also in the logfile.
