### ISSUE TITLE
Burn FLACs 1:1 CD ?

### ISSUE THREAD

**Issue by HanaO00** [JoeLametta/whipper#125]
Hello,

Can we burn FLACs with .cue to get 1:1 copy like EAC ?

**Comment by ArchangeGabriel** [comment]
This is more the job of a CD-writer tool I think. Doesn’t brasero or one of his friend supports that? Or is the issue with having FLACs instead of raw files?

**Comment by kevmitch** [comment]
To clarify, OP probably means ripping to a single file with a cue sheet (possibly embedded) indicating the tracks.

**Comment by HanaO00** [comment]
Hello, i want mean, with EAC we can burn .cue to CD with offset correction to get 1:1 CD writed, can whipper do this ?

Thank you

**Comment by 45054** [comment]
No, it can't. And I don't think, it should.

**Comment by JoeLametta** [comment]
No. You can't do that using just whipper because it's not a pertinent feature.

It can be easily done using [mktoc](https://github.com/cmcginty/mktoc) (cue to toc conversion & offset correction) and cdrdao (burning the generated toc file to a writable cd).
