### ISSUE TITLE
Accurate rip failures still exit 0

### ISSUE THREAD

**Issue by Waiwei8k** [JoeLametta/whipper#126]
When ripping a CD, the rip was successful, but the accurate rip check failed on one of the tracks. I have a scripted flow and would like to be able to respond to this situation.

Could accurate rip failures through an error code please? Ideally a different code to a rip failure so I can filter the files differently.

A subset of the program output is pasted below:

Ripping track 6 of 11: 06. Angelo Badalamenti - The Bookhouse Boys.flac
Checksums match for track 6               
Peak level: 86.76% 
Rip quality: 100.00%

10 AccurateRip reponses found
WARNING:morituri.common.program:Track 06: not matched in AccurateRip database
WARNING:morituri.common.program:Track 06: none of the responses matched.
Track  1: rip accurate     (confidence  97 of 200) [91513e67], DB [91513e67]
Track  2: rip accurate     (confidence  97 of 200) [a1f37661], DB [a1f37661]
Track  3: rip accurate     (confidence  98 of 200) [77f9c8ca], DB [77f9c8ca]
Track  4: rip accurate     (confidence  98 of 200) [01764a23], DB [01764a23]
Track  5: rip accurate     (confidence  99 of 200) [862ae8c4], DB [862ae8c4]
Track  6: rip NOT accurate (max confidence    200) [bf178b4a], DB [ecebf7f0]
Track  7: rip accurate     (confidence  99 of 200) [02b553fc], DB [02b553fc]
Track  8: rip accurate     (confidence  99 of 200) [b0ff7a57], DB [b0ff7a57]
Track  9: rip accurate     (confidence  98 of 200) [60b49de4], DB [60b49de4]
Track 10: rip accurate     (confidence  99 of 200) [cae64747], DB [cae64747]
Track 11: rip accurate     (confidence  96 of 200) [0d50c586], DB [0d50c586]

**Comment by JoeLametta** [comment]
That "possible" issue is also mentioned in the resulting logfile at the end of the rip (and that's the best way to detect it).
Adding new error codes to mark different issues isn't currently planned.

Whipper's internal logger produces YAML-like log reports (so it should be easy to parse). A complete rewrite to make it strictly adherent to the YAML format is planned.
