### ISSUE TITLE
Identify media type in log file (ie CD vs CD-R)

### ISSUE THREAD

**Issue by Scott-Bowman** [JoeLametta/whipper#137]
Not sure if it is technically possible, but it could be a useful feature for a variety of reasons.

**Comment by JoeLametta** [comment]
> Not sure if it is technically possible, but it could be a useful feature for a variety of reasons.

Yeah, I'll check if it can be done.

**Comment by JoeLametta** [comment]
When issuing:

`cdrdao disk-info -v0`

There's a line which reports if the inserted medium is a a CD-R or `n/a` in case it isn't. So, every time we get  the following reply: `CD-R medium          : n/a`, we can mark the disc as a pressed CD, else as a CD-R.

I don't know if that detection is 100% accurate but is should be quite reliable as pressed discs don't have the ATIP (which is always included in writable CD medias).

**Comment by Freso** [comment]
If we're checking for "CD-R", that's what we should report on (ie., "CD-R: True/False"). There are a number of different types of CDs (https://musicbrainz.org/doc/Release/Format), and claiming "Type: CD" vs. "Type: CD-R" could potentially be misleading, IMHO.

**Comment by JoeLametta** [comment]
Completed?
