### ISSUE TITLE
Fix HTOA handling

### ISSUE THREAD

**Issue by PlasmaSheep** [JoeLametta/whipper#14]
Use shardz's patch perhaps?

https://what.cd/forums.php?action=viewthread&threadid=163034&postid=5219467#post5219467

This is the last thing needed for morituri to be whatcd ready.

**Comment by RecursiveForest** [comment]
Perhaps linking to the patch on github instead of a private website is better in this case: https://github.com/thomasvs/morituri/pull/79

**Comment by JoeLametta** [comment]
Well, this has been already merged here: JoeLametta/whipper@468d6cbaf65acf15bcf92a2d7aadf61fa983cece
The author is clearly credited in the commit's description (I've linked to the original pull request).

If there are no changes suggested, I'm closing it.

**Comment by PlasmaSheep** [comment]
Ah yes, I missed that. Closing the issue now.
