### ISSUE TITLE
`whipper find offset` still requiring gst

### ISSUE THREAD

**Issue by r-cheologist** [JoeLametta/whipper#141]
I was excited to follow the work on removing gst dependencies and  just did
`git clone -b master --single-branch https://github.com/JoeLametta/whipper.git`
`cd whipper/src`
`make`
`sudo make install`
`cd ..`
`sudo python2 setup.py develop`
to install it.
But when running `whipper find offset` I end up with 
`Trying read offset 6 ...
Traceback (most recent call last):      
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper', 'console_scripts', 'whipper')()
  File "/home/balin/whipper/morituri/command/main.py", line 39, in main
    raise ImportError(e)
ImportError: No module named gst`

What am I doing wrong?

Joh

**Comment by JoeLametta** [comment]
The reason is that GStreamer removal pull request is currently being reviewed: after that's completed, it's surely going to be merged into whipper's main branch but we haven't done it yet.
