### ISSUE TITLE
Test HTOA peak value against 0 (integer equality)

### ISSUE THREAD

**Issue by JoeLametta** [JoeLametta/whipper#143]
Just resuming what was started in #82.

Things which must be done in order to complete this one:
- [x] Make SoX outputs peaks calculation as integer values on a 16 bit scale
- [x] Update HTOA's comparison code (equality to 0)
- [ ] Update whipper's code paths which use the peak value to reflect the format change

This issue hasn't high priority so it's scheduled for milestone 2.0 (whatever that means).

**Comment by MerlijnWajer** [comment]
I didn't get to reviewing this yet, guess it's no longer necessary?

**Comment by JoeLametta** [comment]
> I didn't get to reviewing this yet, guess it's no longer necessary?

Yep, I wasn't sure that the proposed solution made sense (now it should).

😜
