### ISSUE TITLE
Update doc/release or remove it

### ISSUE THREAD

**Issue by Freso** [JoeLametta/whipper#149]
We've inherited a file `doc/release` from morituri that describes the used release procedure for new morituri releases.

That should either be updated for whipper or removed. @JoeLametta and @MerlijnWajer, which of the two we want to go with is probably mostly your call.

**Comment by MerlijnWajer** [comment]
IMHO we should just drop it.

**Comment by JoeLametta** [comment]
Fixed with #218.
