### ISSUE TITLE
Use 'Artist as credited' in filename instead of 'Artist in MusicBrainz' (e.g. to solve [unknown])

### ISSUE THREAD

**Issue by gorgobacka** [JoeLametta/whipper#155]
If in MusicBrainz an artist is referenced to [unknown], whipper uses this in the filenames. I think it makes more sense to use the 'Artist as credited'.

Additionally, it would be consistent with the names used on the disc (Artist as credited).

**Comment by JoeLametta** [comment]
Solved with #156.
