### ISSUE TITLE
NameError: global name 'musicbrainz' is not defined

### ISSUE THREAD

**Issue by neitsab** [JoeLametta/whipper#16]
I have the following error when trying to run whipper after building the latest checkout:

```python
# rip -h
Traceback (most recent call last):
  File "/usr/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 39, in main
    musicbrainz.set_useragent("morituri", configure.version,
NameError: global name 'musicbrainz' is not defined
```
No matter what I try (installing `python2-musicbrainz2` besides `python2-musicbrainzngs`...), it doesn't change anything. Suspecting 89f3ba3 to be at play here :)

This is on Arch Linux, running in a clean x64 chroot used for the build (I'm trying to package whipper for the AUR).

Thanks for your work on reviving morituri!

**Comment by JoeLametta** [comment]
@neitsab Please test again with my latest commit to check if this solves the issue you are reporting.
Thanks for the feedback!

**Comment by neitsab** [comment]
Success it works, thanks for your prompt answer @JoeLametta!
