### ISSUE TITLE
Minimal makedepends for building

### ISSUE THREAD

**Issue by neitsab** [JoeLametta/whipper#17]
As I'm currently trying to package whipper for the AUR, I narrowed down the smallest set of requirements for *building* it successfully:

- `python2-gobject2`
- `python2-musicbrainzngs`
- `python2-setuptools`

Those were enough to correctly build it from a git checkout. I can post the rest of the `PKGBUILD`/build process is there is interest, but I'm waiting feedback on #16 to get it to run :)

Cheers

**Comment by JoeLametta** [comment]
Sure.
An "official" AUR package is certainly welcomed!
