### ISSUE TITLE
using your own MusicBrainz server

### ISSUE THREAD

**Issue by Fish2** [JoeLametta/whipper#172]
would be nice if we could use your own MusicBrainz server if we have one

**Comment by Freso** [comment]
(Might also be useful for development purposes so you can set up your own server and make some garbage edits to test stuff (e.g., #166 etc.) without polluting the real db.)

**Comment by RecursiveForest** [comment]
I could definitely see making this an optional configuration file entry.

**Comment by naiveaiguy** [comment]
Starting work on this.

**Comment by naiveaiguy** [comment]
Sorry about the false references, I've been doing a lot of `--amend`s on that PR so the SHA changes.

**Comment by JoeLametta** [comment]
> Sorry about the false references, I've been doing a lot of --amends on that PR so the SHA changes.

No problem! 😜 
Thanks for the PR.
