### ISSUE TITLE
Whipper offset find failing

### ISSUE THREAD

**Issue by Q3CPMA** [JoeLametta/whipper#177]
Hello,
after running `whipper drive analyze` correctly, `whipper offset find -o +6` fails with the following:
```
> whipper offset find -o +6
Checking device /dev/sr0
Trying read offset 6 ...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/morituri/common/checksum.py", line 73, in _arc
    self._wave, self._v2)
  File "/usr/lib64/python2.7/site-packages/morituri/program/arc.py", line 24, in accuraterip_checksum
    stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
WARNING:morituri.command.offset:Unknown task exception for offset 6: TaskException(OSError(2, 'No such file or directory'), 'exception OSError at /usr/lib64/python2.7/subprocess.py:1343: _execute_child(): [Errno 2] No such file or directory\nTraceback (most recent call last):\n  File "/usr/lib64/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c\n    callable(*args, **kwargs)\n  File "/usr/lib64/python2.7/site-packages/morituri/common/checksum.py", line
73, in _arc\n    self._wave, self._v2)\n  File "/usr/lib64/python2.7/site-packages/morituri/program/arc.py", line 24, in accuraterip_checksum\n    stdout=PIPE, stderr=PIPE)\n  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__\n    errread, errwrite)\n  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n')
WARNING: cannot rip with offset 6...
No matching offset found.
Consider trying again with a different disc.
```
With the 0.5.1 release, an LG BDDVDRW CH12NS30 drive and three different CDs. I have run `whipper drive analyze` successfully.

**Comment by JoeLametta** [comment]
It looks like you haven't installed all the required dependencies: `accuraterip-checksum` appears to be missing.
The correct way to install whipper is documented in the [README](https://github.com/JoeLametta/whipper). The section which provides the instructions for installing `accuraterip-checksum` is [this one](https://github.com/JoeLametta/whipper#building-the-bundled-dependencies).

I think #178 is caused by the missing dependency too.

**Comment by Q3CPMA** [comment]
That's what I thought too. I tried to convert the Arch PKGBUILD into an ebuild, but I didn't see that these executables were de-bundled.
Thanks for the help.

**Comment by Q3CPMA** [comment]
Now the problem is different, I get this:
```
$ whipper offset find -o +6
Checking device /dev/sr0
Trying read offset 6 ...
No matching offset found.
```
With every disc I tried, even if my disc is an "LG Electronics - BDDVDRW CH12NS30" with +6 in here http://www.accuraterip.com/driveoffsets.htm

**Comment by Q3CPMA** [comment]
I got 48 by running `whipper offset find`. Is this possible to have a different result than the accurip db?

**Comment by RecursiveForest** [comment]
Do the CDs you rip verify against the accuraterip DB?

**Comment by JoeLametta** [comment]
Closed (few months without any reply from the OP).
