### ISSUE TITLE
Various ripping issues

### ISSUE THREAD

**Issue by Q3CPMA** [JoeLametta/whipper#179]
- `wihpper cd rip` doesn't exit after fetching and displaying metadata (even if it can't do anything without `-p` or `-R`).
- After selecting the release (with `-p`), there's no way to know it's not stuck (maybe some progress status or at least a message?). Only by seeing the cdrdao CPU usage we can know it's doing something.
- `whipper cd rip -h` lacks newlines between the template format description entries.
```
Rips a CD. Tracks are named according to the track template, filling in the
variables and adding the file extension. Variables exclusive to the track
template are:
- %t: track number
- %a: track artist
- %n: track title
- %s: track sort name
Disc files (.cue, .log, .m3u) are named according to the disc
template, filling in the variables and adding the file extension. Variables
for both disc and track template are:
- %A: album artist
- %S: album sort name
- %d: disc title
- %y: release year 
- %r: release type, lowercase
- %R: Release type, normal case
- %x: audio extension, lowercase
- %X: audio extension, uppercase
Paths to track files referenced in .cue and .m3u files
will be made relative to the directory of the disc files. All files will be
created relative to the given output directory. Log files will log the path to
tracks relative to this directory.
```
instead of
```
Rips a CD. Tracks are named according to the track template, filling in the
variables and adding the file extension. Variables exclusive to the track
template are: - %t: track number - %a: track artist - %n: track title - %s:
track sort name Disc files (.cue, .log, .m3u) are named according to the disc
template, filling in the variables and adding the file extension. Variables
for both disc and track template are: - %A: album artist - %S: album sort name
- %d: disc title - %y: release year - %r: release type, lowercase - %R:
Release type, normal case - %x: audio extension, lowercase - %X: audio
extension, uppercase Paths to track files referenced in .cue and .m3u files
will be made relative to the directory of the disc files. All files will be
created relative to the given output directory. Log files will log the path to
tracks relative to this directory.
```

**Comment by RecursiveForest** [comment]
Thanks for the bug reports.

 For me, if a disc has multiple matching releases on MusicBrainz and `-p` is not passed, it prints the metadata for each release and then exits with return code 255, unless `-U` is passed in which case it rips the disc without metadata. Could you give me more information on how you executed whipper to help me recreate?

I agree that whipper is fairly incommunicative about running cdrdao to read the toc, and that the documentation formatting needs some attention; I'm going to deal with those separately.

**Comment by JoeLametta** [comment]
Progress update for this issue...

- [x] After selecting the release (with -p), there's no way to know it's not stuck (maybe some progress status or at least a message?). Only by seeing the cdrdao CPU usage we can know it's doing something.
- [x] whipper cd rip -h lacks newlines between the template format description entries.
- [ ] wihpper cd rip doesn't exit after fetching and displaying metadata (even if it can't do anything without -p or -R).

**Comment by JoeLametta** [comment]
> For me, if a disc has multiple matching releases on MusicBrainz and -p is not passed, it prints the metadata for each release and then exits with return code 255. Could you give me more information on how you executed whipper to help me recreate?

@Q3CPMA I haven't checked the remaining issue but could you answer RecursiveForest's question?

Thanks,
Joe

**Comment by Q3CPMA** [comment]
Honestly, just close the remaining one. I don't remember encountering such issue
an additional time (maybe the first time was a dud too).

**Comment by JoeLametta** [comment]
> Honestly, just close the remaining one.

Understood, thanks for the reply!
