### ISSUE TITLE
.log, .cue, and .m3u file names

### ISSUE THREAD

**Issue by spacecactus** [JoeLametta/whipper#180]
Hello, I'm using whipper 0.5.1 on Debian 9 (Stretch) and there seems to be a bug where the .log, .cue, and playlist files all have the file name of  "00 - Hidden Track One Audio". This occurs regardless as to whether the CD has a hidden track one or not.
![whipperhiddenfilename](https://user-images.githubusercontent.com/30816295/29052383-576f1740-7baf-11e7-8833-d701633cfc6d.jpg)

Here are some sample ripping processes and logs:
Blue Oyster Cult - Don't Fear The Reaper Best Of
[process-blue-oyster-cult.txt](https://github.com/JoeLametta/whipper/files/1206645/process-blue-oyster-cult.txt)
[00 - Hidden Track One Audio.txt](https://github.com/JoeLametta/whipper/files/1206647/00.-.Hidden.Track.One.Audio.txt)

Pink Floyd - Dark Side Of The Moon
[process-pink-floyd.txt](https://github.com/JoeLametta/whipper/files/1206648/process-pink-floyd.txt)
[00 - Hidden Track One Audio.txt](https://github.com/JoeLametta/whipper/files/1206649/00.-.Hidden.Track.One.Audio.txt)

Dave Brubeck - Time Out
[process-dave-brubeck.txt](https://github.com/JoeLametta/whipper/files/1206650/process-dave-brubeck.txt)
[00 - Hidden Track One Audio.txt](https://github.com/JoeLametta/whipper/files/1206651/00.-.Hidden.Track.One.Audio.txt)

The argument used to call whipper is:

> $ whipper cd rip -L whipper -O ~/rips --track-template "%A - %d (%y)/%t - %n" --disc-template "%A - %d (%y)/%t - %n"

and the config file is:

[whipper.txt](https://github.com/JoeLametta/whipper/files/1206661/whipper.txt)

**Comment by xmixahlx** [comment]
The track template includes track number and name (?). I am assuming that this will always be 00 HTOA because it is the first track processed. Either way, you don't want the disc named any of the track numbers and titles, I assume.

Use --disc-template "%A - %d (%y)/%A - %d (%y)" or something similar.

**Comment by spacecactus** [comment]
Yes, it wasn't clear from the readme the function of --disc-template. Thank you.

> whipper cd rip -L whipper -O ~/rips --track-template "%A - %d (%y)/%t - %n" --disc-template "%A - %d (%y)/%A - %d (%y)"
is what I needed. This issue can be closed.
