### ISSUE TITLE
CD-ROM powers off during rip command.

### ISSUE THREAD

**Issue by Niralith** [JoeLametta/whipper#189]
whipper-git 0.5.1.r46.g47842c2-1
Arch x86_64

I've got a curious issue. One that I'm unsure if it belongs here. Like stated my external cd-drive (LG Electronics - DVDRAM GSA-4082N) powers off and becomes unresponsive during the execution of

> `whipper cd rip -R bfe6-6358-4f7c-9f1c-20941485e350 -L whipper --track-template "%A - %d/%t - %n" --disc-template "%A - %d - %y"`

command. Now I'm not exactly sure if it's whipper or cdrdao at fault. As can be seen the log ends after passing 

> `whipper.program.cdrdao:executing ['cdrdao', 'disk-info', '-v1', '--device', '/dev/sr0']`

Since running command `whipper drive analyze` or `whipper offset find` does not result in similar behaviour, it would seem that the cdrdao is the most probable culprit. This notion is further reinforced by the fact that I can rip this cd while using SoundKonverter or abcde. Log and screenshot results of lsblk attached.
Like stated, wasn't sure if this bug report should go here or to cdrdao, but decided that you still would probably like to know.

[whipper.log.tar.gz](https://github.com/JoeLametta/whipper/files/1289879/whipper.log.tar.gz)

**Comment by JoeLametta** [comment]
Thanks for reporting this issue.
Could you test what happens if you run the following commands against that drive?

```
umount /dev/sr0 # run as superuser if needed
cdrdao disk-info -v1 --device /dev/sr0 # please, post the output of this command
```

Thanks,
Joe

**Comment by JoeLametta** [comment]
@Niralith Bump.
