### ISSUE TITLE
get rid of the gstreamer-0.10 dependency

### ISSUE THREAD

**Issue by PlasmaSheep** [JoeLametta/whipper#2]

**Comment by JoeLametta** [comment]
Ongoing discussion about this one can be found here: thomasvs/morituri#47
User [alexvong1995](https://github.com/alexvong1995/morituri/tree/gst-1.x) said he will try to work on this one during the holidays.

**Comment by PlasmaSheep** [comment]
That's good, considering that I don't have much experience with gstreamer. It's not too high of a priority since it works currently and not a blocker for being an approved ripper.

**Comment by xmixahlx** [comment]
Is there any update?

Resolving the gstreamer 0.10 situation seems incredibly important from a packaging perspective (Debian!).

I've been able to sidestep the issue on Debian Unstable by checking out the sources from Jessie, some packaging modifications and build-deps (updated libraries, etc.), and rebuilding the gst-plugins-good package (I just rebuilt all of them...).

Whipper is working great on Debian Unstable now. Thanks!

**Comment by JoeLametta** [comment]
If I recall correctly this was being worked on (finished?) by @MerlijnWajer for another project and it results in a complete overhaul to the codebase.
It still needs to be rebased for whipper but hopefully it shouldn't take too long.

In the next days I won't be able to reply. For any questions regarding this one, please ask @RecursiveForest

**Comment by JoeLametta** [comment]
Discussion about this one will continue on issue #29.
