### ISSUE TITLE
Migrate away from the "rip" command

### ISSUE THREAD

**Issue by baldurmen** [JoeLametta/whipper#21]
Hi!

I've been thinking for a while now that morituri's `rip` command is pretty badly named. Normally, when you download a program you kinda expect to be able to call it by it's name and not some other name!

Since you decided to fork morituri, I find it even more confusing, since both of them now use the same utility name...

Why don't you migrate away from it and use `whipper` as the way to call the program?

**Comment by JoeLametta** [comment]
Sure, this needs to be done... (it's a long time plan)
The migration would also take care of improving whipper's command parsing structure. Regarding this topic I received the following suggestion I'd like to use as reference:
 
rip cd rip -> whipper rip /dev/srX
of rip cd info -> whipper info /dev/srX
whipper analyze /dev/srX (it would combine rip offset find and rip drive analyze)
The /dev/srX argument would be optional.

**Comment by baldurmen** [comment]
I think specifying the drive is a wonderful idea, especially for people
who (like I) use a multi-drive setup to save time.

**Comment by Voidi** [comment]
I totally agree with renaming the `rip` command to the project names, but why renaming the project?
Assuming the original the original author has dropped the project, this version would be the only one   and nobody would be confused. And i really like the joke with name morituri.

**Comment by JoeLametta** [comment]
@Voidi Well that should be discussed with @thomasvs but, at the moment, I think it's better this way (less confusing). I've not really planned it thoroughly for the long term (definitive name is still undecided) but, even in the perspective of package maintainers^, using a different name could be a good thing.

Thanks for raising this point, hopefully others will comment on this one too.

^ When milestone 1.0 will be reached I'll try to get it officially packaged (starting with Debian, Ubuntu, Fedora).

**Comment by xmixahlx** [comment]
Whipper seems like a true fork. Unless Morituri is actually defunct, it
should be renamed. I vote Whipper.

It will be way easier to package, also.

**Comment by RecursiveForest** [comment]
I +1 calling the executable `whipper` since we can't seem to find a better project name.
