### ISSUE TITLE
TRACK and FILE order in cue file

### ISSUE THREAD

**Issue by sphh** [JoeLametta/whipper#212]
I got a cue file by ripping OVO from Peter Gabriel:
```
REM DISCID 8E0E880C
REM COMMENT "whipper 0.5.1"
FILE "01. Peter Gabriel - The Story of OVO.flac" WAVE
  TRACK 01 AUDIO
    ISRC GBCPB0000017
    INDEX 01 00:00:00
FILE "02. Peter Gabriel - Low Light.flac" WAVE
  TRACK 02 AUDIO
    ISRC GBCPB0000003
    INDEX 01 00:00:00
FILE "03. Peter Gabriel - The Time of the Turning.flac" WAVE
  TRACK 03 AUDIO
    ISRC GBCPB0000004
    INDEX 01 00:00:00
FILE "04. Peter Gabriel - The Man Who Loved the Earth - The Hand That Sold Shadows.flac" WAVE
  TRACK 04 AUDIO
    ISRC GBCPB0000005
    INDEX 01 00:00:00
FILE "05. Peter Gabriel - The Time of the Turning (reprise) - The Weavers Reel.flac" WAVE
  TRACK 05 AUDIO
    ISRC GBCPB0000007
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    ISRC GBCPB0000008
    INDEX 00 05:35:25
FILE "06. Peter Gabriel - Father, Son.flac" WAVE
    INDEX 01 00:00:00
FILE "07. Peter Gabriel - The Tower That Ate People.flac" WAVE
  TRACK 07 AUDIO
    ISRC GBCPB0000009
    INDEX 01 00:00:00
FILE "08. Peter Gabriel - Revenge.flac" WAVE
  TRACK 08 AUDIO
    ISRC GBCPB0000010
    INDEX 01 00:00:00
FILE "09. Peter Gabriel - White Ashes.flac" WAVE
  TRACK 09 AUDIO
    ISRC GBCPB0000011
    INDEX 01 00:00:00
FILE "10. Peter Gabriel - Downside‐Up.flac" WAVE
  TRACK 10 AUDIO
    ISRC GBCPB0000012
    INDEX 01 00:00:00
FILE "11. Peter Gabriel - The Nest That Sailed the Sky.flac" WAVE
  TRACK 11 AUDIO
    ISRC GBCPB0000013
    INDEX 01 00:00:00
FILE "12. Peter Gabriel - Make Tomorrow.flac" WAVE
  TRACK 12 AUDIO
    ISRC GBCPB0000015
    INDEX 01 00:00:00
```
You can see that after `FILE "05. ...` the order of `TRACK` and `FILE` entries are somewhat strange. Is this how it should be?

For a comparison here is the toc file from `cdrdao read-toc`:
```
CD_DA


// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000017"
FILE "data.wav" 0 05:21:30


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000003"
FILE "data.wav" 05:21:30 06:37:17


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000004"
FILE "data.wav" 11:58:47 05:05:63


// Track 4
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000005"
FILE "data.wav" 17:04:35 04:14:70


// Track 5
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000007"
FILE "data.wav" 21:19:30 05:35:25


// Track 6
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000008"
FILE "data.wav" 26:54:55 04:57:50
START 00:01:32


// Track 7
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000009"
FILE "data.wav" 31:52:30 04:49:60


// Track 8
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000010"
FILE "data.wav" 36:42:15 01:30:07


// Track 9
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000011"
FILE "data.wav" 38:12:22 02:34:25


// Track 10
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000012"
FILE "data.wav" 40:46:47 06:04:73


// Track 11
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000013"
FILE "data.wav" 46:51:45 05:06:12


// Track 12
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBCPB0000015"
FILE "data.wav" 51:57:57 10:02:70
```

The log files are

- `whipper`: [Peter Gabriel-OVO.log](https://github.com/JoeLametta/whipper/files/1629432/Peter.Gabriel-OVO.log)
- `cdrdao`: [ovo1.log](https://github.com/JoeLametta/whipper/files/1629433/ovo1.log)

**Comment by kevmitch** [comment]
I think this is to account for gaps (see what happens on track 5).

**Comment by 45054** [comment]
Yep. This is the intended behaviour. See: http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Multiple_files_with_gaps_.28Noncompliant.29

**Comment by sphh** [comment]
Thank you for the explanation. I was only comparing it to the standard definition of the cue file and missed that non-compliant "quirk".

How do I write it back to a CD? I tried on my Linux Mint 18.3 box:
```
$ cdrdao write Peter\ Gabriel-OVO.cue 
Cdrdao version 1.2.3 - (C) Andreas Mueller <andreas@daneb.de>
Pregap out of range
```

When I convert the cue to a toc file, I get the same error:
```
$ cue2toc -o Peter\ Gabriel-OVO.toc Peter\ Gabriel-OVO.cue 
cue2toc: Pregap out of range
```

The toc file written is:
```// Generated by cue2toc 0.4
// Report bugs to <dermatsch@gmx.de>
CD_DA

TRACK AUDIO
    ISRC "GBCPB0000017"
    AUDIOFILE "01. Peter Gabriel - The Story of OVO.flac" 00:00:00

TRACK AUDIO
    ISRC "GBCPB0000003"
    AUDIOFILE "02. Peter Gabriel - Low Light.flac" 00:00:00

TRACK AUDIO
    ISRC "GBCPB0000004"
    AUDIOFILE "03. Peter Gabriel - The Time of the Turning.flac" 00:00:00

TRACK AUDIO
    ISRC "GBCPB0000005"
    AUDIOFILE "04. Peter Gabriel - The Man Who Loved the Earth - The Hand That Sold Shadows.flac" 00:00:00

TRACK AUDIO
    ISRC "GBCPB0000007"
    AUDIOFILE "05. Peter Gabriel - The Time of the Turning (reprise) - The Weavers Reel.flac" 00:00:00 05:35:25

TRACK AUDIO
    ISRC "GBCPB0000008"
    AUDIOFILE "05. Peter Gabriel - The Time of the Turning (reprise) - The Weavers Reel.flac" 05:35:25
```

**Comment by JoeLametta** [comment]
> How do I write it back to a CD?

I think you can use [mktoc](https://github.com/cmcginty/mktoc) to convert the non-compliant cue sheet to a "valid" toc file which cdrdao should be capable of burning.
Please test and let us know how it goes.

**Comment by sphh** [comment]
Thanks!

The following work-flow worked:
1. Edit the .cue file written by `whipper` and replace all file endings `.flac` with `.wav`.
2. Convert all flac files to wav files (`flac -d file.flac`).
3. Convert the .cue file to a .toc file (`mktoc -f file.cue > file.toc`).
4. If you don't want to keep the .wav files:
    a. Edit the .toc file and replace all file endings `.wav` with `.flac` (optional).
    b. Delete all .wav generated in step 2.
5. Burn the disk (`cdrdao file.toc`).

It would be nice, if the functionality of `mktoc` could be incorporated into `whipper`, so that `whipper` could also write .toc files...

**Comment by JoeLametta** [comment]
> It would be nice, if the functionality of mktoc could be incorporated into whipper, so that whipper could also write .toc files...

Thanks for the test.
I think that including mktoc's features in whipper would be a bit out of the scope for the project. What can be surely done is:

1. Document this work-flow for burning CDs (mktoc + cdrdao)
2. Contribute to mktoc's (I'll try to open a pull request to port the tool to Python 3)

**Comment by JoeLametta** [comment]
Number two has been completed. I've opened a pull request here: https://github.com/cmcginty/mktoc/pull/8.
Will probably complete number 1 later next week.

**Comment by sphh** [comment]
Hi @JoeLametta ,

Sorry for not letting this drop: What I meant, was not that `whipper` converts cue to toc files (that's the job of `mktoc`, but that `whipper` writes toc files natively?

**Comment by JoeLametta** [comment]
> Hi @JoeLametta ,
> 
> Sorry for not letting this drop: What I meant, was not that whipper converts cue to toc files (that's the job of mktoc, but that whipper writes toc files natively?

No problem: got it now. I'll investigate if it's easily doable.
I'd like you to open a new issue describing your proposal so that we don't forget it.

Thanks,
Joe
