### ISSUE TITLE
Make a 0.6.0 release

### ISSUE THREAD

**Issue by Freso** [JoeLametta/whipper#219]
There have been a number of significant patches/PRs merged since [v0.5.1](https://github.com/JoeLametta/whipper/releases/tag/v0.5.1). whipper no longer uses any morituri namespace, so the two could be installed side-by-side, it now uses libcdio-paranoia instead of cdparanoia, AccurateRip v2 support has been added, etc., etc.

I know we want 1.0.0 to be released ASAP, but I think making a 0.6.0 release now would be good to let packagers start making packages with the new dependencies (libcdio-paranoia and python(2)-requests) and to get the current state-of-the-code into more users' hands for wider testing, to possibly find any/more regressions before a "final" 1.0.0 release is made.

I think it would be fine to just set the 0.6.0 release at the HEAD of the current `master` branch, this is still a pre-release release.

**Comment by MerlijnWajer** [comment]
In addition, I would propose that odd numbered releases are perhaps considered testing/beta releases, and even numbers ones stables ones? But then 0.7 would make more sense.. :)

**Comment by Freso** [comment]
I disagree with that. :) Let's stick to [semver](https://semver.org/) and use -beta etc. postfixes for testing releases. (Note that anything <1.0.0 is a testing/unstable release in semver: «4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.»)

**Comment by JoeLametta** [comment]
Good idea.
I've found the following changes to be backward incompatible, am I missing any other?

- Fix references to morituri. (#109) // Renamed module, logger
- Detect and handle CD-R discs (#154) // Prevents ripping CD-R discs by default
- AccurateRip V2 support (#187) // Various changes, new dependency: `requests`
- Switch to libcdio-cdparanoia (from cdparanoia) (#213) // Changed dependency

**Comment by JoeLametta** [comment]
> Let's stick to semver

We don't have a defined API: how do we deal with this?

**Comment by MerlijnWajer** [comment]
We do have an API, it's just internal. We don't really have to worry about this until we support 'library usage', as I have hacked morituri to do.

**Comment by Freso** [comment]
We also have an external "API": `whipper <global arguments> <command> <command arguments>` + the configuration file.

Altering the commands/arguments or the configuration file in a non-backwards compatible way would require a new major version according to SemVer.

**Comment by Freso** [comment]
I look over https://github.com/JoeLametta/whipper/compare/v0.5.1...master and I don't see any backwards incompatible changes other than the ones @JoeLametta mentioned in his comment before.

**Comment by JoeLametta** [comment]
Will tag it later today.

**Comment by JoeLametta** [comment]
Done: [v0.6.0](https://github.com/JoeLametta/whipper/releases/tag/v0.6.0).

:wink:
