### ISSUE TITLE
How to choose device (if there are more)?

### ISSUE THREAD

**Issue by TJFOE** [JoeLametta/whipper#241]
How could the device be choosen? I.e. instead of  /dev/sr0 should be used  /dev/sr1.

**Comment by mruszczyk** [comment]
What's the output of whipper drive list for you? It should be whipper cd -d (device) rip

**Comment by TJFOE** [comment]
tom@tom-kubuntu:~$ whipper drive list
drive: /dev/cdrom, vendor: HL-DT-ST, model: BD-RE  BH16NS40 , release: 1.01
       No read offset found.  Run 'whipper offset find'
       Unknown whether audio cache can be defeated. Run 'whipper drive analyze'
drive: /dev/dvd, vendor: Optiarc , model: DVD RW AD-7240S , release: 1.04
       No read offset found.  Run 'whipper offset find'
       Unknown whether audio cache can be defeated. Run 'whipper drive analyze'
tom@tom-kubuntu:~$ whipper cd -d /dev/dvd rip
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/main.py", line 39, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 102, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 102, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 89, in __init__
    self.handle_arguments()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/cd.py", line 300, in handle_arguments
    raise ValueError("Drive offset is unconfigured.\n"
ValueError: Drive offset is unconfigured.
Please install pycdio and run 'whipper offset find' to detect your drive's offset or set it manually in the configuration file. It can also be specified at runtime using the '--offset=value' argument

**Comment by TJFOE** [comment]
pycdio 17 is installed. The real offset of  /dev/sr0 is "+6". The other device /dev/sr1 could not be used.

whipper offset find
Checking device /dev/sr0
Trying read offset 6 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 6...    
Trying read offset 48 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 48...    
Trying read offset 102 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 102...    
Trying read offset 667 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 667...    
Trying read offset 12 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 12...     
Trying read offset 30 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 30...     
Trying read offset 618 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 618...    
Trying read offset 594 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 594...    
Trying read offset 738 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 738...    
Trying read offset -472 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -472...    
Trying read offset 98 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 98...      
Trying read offset 116 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 116...     
Trying read offset 96 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 96...      
Trying read offset 733 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 733...     
Trying read offset 120 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 120...     
Trying read offset 691 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 691...     
Trying read offset 685 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 685...     
Trying read offset 97 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 97...      
Trying read offset 600 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 600...     
Trying read offset 690 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 690...     
Trying read offset 1292 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 1292...    
Trying read offset 99 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 99...      
Trying read offset 676 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 676...     
Trying read offset 686 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 686...     
Trying read offset 1182 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 1182...    
Trying read offset -24 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -24...     
Trying read offset 704 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 704...     
Trying read offset 572 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 572...     
Trying read offset 688 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 688...     
Trying read offset 91 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 91...      
Trying read offset 696 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 696...     
Trying read offset 103 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 103...     
Trying read offset -491 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -491...    
Trying read offset 689 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 689...     
Trying read offset 145 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 145...     
Trying read offset 708 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 708...     
Trying read offset 697 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 697...     
Trying read offset 564 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 564...     
Trying read offset 86 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 86...      
Trying read offset 679 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 679...     
Trying read offset 355 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 355...     
Trying read offset -496 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -496...    
Trying read offset -1164 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -1164...    
Trying read offset 1160 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 1160...     
Trying read offset 694 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 694...      
Trying read offset 0 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 0...        
Trying read offset -436 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset -436...     
Trying read offset 79 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 79...       
Trying read offset 94 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 94...       
Trying read offset 684 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 684...      
Trying read offset 681 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 681...      
Trying read offset 106 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):          
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/main.py", line 40, in main
    ret = cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/offset.py", line 121, in do
    archecksums = self._arcs(runner, table, 1, offset)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/offset.py", line 195, in _arcs
    runner.run(t)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/extern/task/task.py", line 528, in run
    task.exceptionMessage, task.exceptionTraceback))
MemoryError

**Comment by mruszczyk** [comment]
Your offset should be +48.

If everything is installed properly you should be able to do:
`whipper drive analyze -d /dev/dvd`

`whipper offset find -o 48 -d /dev/dvd`

`whipper cd -d /dev/dvd rip -o 48` if the command above confirms your drives offset is 48.

**Comment by TJFOE** [comment]
My offset for Optiarc AD-7240S is +48. This is /dev/sr1.

HL-DT-ST, model: BD-RE BH16NS40 offset is "+6" and is /dev/sr0.

With or without reference cd I get always:

tom@tom-kubuntu:~$ whipper drive analyze -d /dev/dvd
Cannot analyze the drive.  Is there a CD in it?
tom@tom-kubuntu:~$ whipper drive analyze -d /dev/cdrom
Cannot analyze the drive.  Is there a CD in it?

**Comment by mruszczyk** [comment]
I believe this is a bug in older versions of cd-paranoia. I have an email from a user on Centos who installed via the copr and his analyze command does not work as well. What version of libcdio-paranoia do you have?

**Comment by TJFOE** [comment]
Please have a look at this https://github.com/JoeLametta/whipper/issues/238

This works!!! The first time ... 
whipper cd -d /dev/dvd rip -o 6

**Comment by TJFOE** [comment]
Oh not complete ...

Checking device /dev/sr1
CDDB disc id: 38098c05
MusicBrainz disc id m8auNQ4AhMtJjW14Hnz.uezmcWg-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+5+183465+183+51735+90810+126230+165433&tracks=5&id=m8auNQ4AhMtJjW14Hnz.uezmcWg-
Disc duration: 00:40:43.760, 5 audio tracks
WARNING:whipper.common.mbngs:Release with ID 'a52c0c4d-475a-3a4d-8119-7bccd3aafb12' (Paco de Lucía, Al Di Meola & John McLaughlin - Friday Night in San Francisco) does not have a date

Matching releases:

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/047070ec-c8a7-319c-a5b5-15c8b5f30c0c
Release : 047070ec-c8a7-319c-a5b5-15c8b5f30c0c
Type    : Live
Barcode : 042280004729
Cat no  : 800 047-2

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/35a2864f-abd8-424c-a1f9-3b3454063dab
Release : 35a2864f-abd8-424c-a1f9-3b3454063dab
Type    : Live

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/a52c0c4d-475a-3a4d-8119-7bccd3aafb12
Release : a52c0c4d-475a-3a4d-8119-7bccd3aafb12
Type    : Live
Barcode : 07464371522
Cat no  : CK 37152

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/a67687ec-9caf-365e-900b-e24eefc568c0
Release : a67687ec-9caf-365e-900b-e24eefc568c0
Type    : Live
Barcode : 5099748900722
Cat no  : COL 489007 2

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/d21a8f9b-68ec-37a0-8903-8657bd853df7
Release : d21a8f9b-68ec-37a0-8903-8657bd853df7
Type    : Live
Cat no  : 35DP 9

creating output directory ./live/Paco de Lucía, Al Di Meola & John McLaughlin - Friday Night in San Francisco
found Hidden Track One Audio from frame 0 to 32
Ripping track 0 of 5: 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 2): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 3): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 4): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 5): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
CRITICAL:whipper.command.cd:Giving up on track 0 after 5 times
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'

**Comment by mruszczyk** [comment]
I believe you're mixing up your offsets there. /dev/cdrom (Hitachi Blu-Ray Drive) should be -o 6 and /dev/dvd (Optiarc) should be -o 48 according to the list. Can you try again selecting the correct drive and matching offset?

**Comment by TJFOE** [comment]
Yes, you are right. But...:

tom@tom-kubuntu:~$ whipper cd -d /dev/dvd rip -o 48
Checking device /dev/sr1
CDDB disc id: 38098c05
MusicBrainz disc id m8auNQ4AhMtJjW14Hnz.uezmcWg-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+5+183465+183+51735+90810+126230+165433&tracks=5&id=m8auNQ4AhMtJjW14Hnz.uezmcWg-
Disc duration: 00:40:43.760, 5 audio tracks
WARNING:whipper.common.mbngs:Release with ID 'a52c0c4d-475a-3a4d-8119-7bccd3aafb12' (Paco de Lucía, Al Di Meola & John McLaughlin - Friday Night in San Francisco) does not have a date

Matching releases:

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/047070ec-c8a7-319c-a5b5-15c8b5f30c0c
Release : 047070ec-c8a7-319c-a5b5-15c8b5f30c0c
Type    : Live
Barcode : 042280004729
Cat no  : 800 047-2

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/35a2864f-abd8-424c-a1f9-3b3454063dab
Release : 35a2864f-abd8-424c-a1f9-3b3454063dab
Type    : Live

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/a52c0c4d-475a-3a4d-8119-7bccd3aafb12
Release : a52c0c4d-475a-3a4d-8119-7bccd3aafb12
Type    : Live
Barcode : 07464371522
Cat no  : CK 37152

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/a67687ec-9caf-365e-900b-e24eefc568c0
Release : a67687ec-9caf-365e-900b-e24eefc568c0
Type    : Live
Barcode : 5099748900722
Cat no  : COL 489007 2

Artist  : Paco de Lucía, Al Di Meola & John McLaughlin
Title   : Friday Night in San Francisco
Duration: 00:40:43.559
URL     : https://musicbrainz.org/release/d21a8f9b-68ec-37a0-8903-8657bd853df7
Release : d21a8f9b-68ec-37a0-8903-8657bd853df7
Type    : Live
Cat no  : 35DP 9

output directory ./live/Paco de Lucía, Al Di Meola & John McLaughlin - Friday Night in San Francisco already exists
found Hidden Track One Audio from frame 0 to 32
Ripping track 0 of 5: 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 2): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 3): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 4): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 0 of 5 (try 5): 00. Paco de Lucía, Al Di Meola & John McLaughlin - Hidden Track One Audio.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 77660
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
CRITICAL:whipper.command.cd:Giving up on track 0 after 5 times
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'

**Comment by mruszczyk** [comment]
Looks related to this. https://github.com/JoeLametta/whipper/issues/234

**Comment by TJFOE** [comment]
Yes. Thank you!

**Comment by TJFOE** [comment]
By the way: Is there a way to set "--output-directory" and "--track-template" like in morituri?

**Comment by mruszczyk** [comment]
Yup, `whipper cd -d /dev/dvd rip -o 48 -O ~/rips/disc1`

Select any directory you can write to. you can run whipper <command> -h to get any flags the command can accept. So for the rip command, full options are `whipper cd rip -h`

**Comment by TJFOE** [comment]
Thanks again!

**Comment by TJFOE** [comment]
Sorry ... and how can the output format be set? If I want wav, i.e.? In Morituri there was --profile, which I don't find here...

**Comment by mruszczyk** [comment]
Unsupported and was removed. https://github.com/JoeLametta/whipper/issues/184

**Comment by RecursiveForest** [comment]
Please do not open github issues for personal support requests. You can drop by our IRC channel at freenode.net #whipper .
