### ISSUE TITLE
Statement to your "only flac" decision

### ISSUE THREAD

**Issue by TJFOE** [JoeLametta/whipper#247]
I will leave a statement to your decision not to go on like morituri or EAC to make an output of wav files available. Whipper will only output flac.

People who where using EAC or morituri up to now are people who want exact results of their rips. It is the same kind of people who love (real) high end audio. For many people it makes no difference listening to flacs, played by using the flac-library. But if you are any kind of perfectionist, you can hear differences and you will do this:

- Using low latency commandline Linux like ArchLinux and patching a realtime kernel
- Software-Player: Against software induced jitter you could go with very lean library-power while playing music. I.e.: Open a wav-file header (using a library or reading the first bytes), read its offset and the other parameters, close the library, read the raw data to memory and play it - only using the Alsa library.

You could use also wavpack: Reading with wavpack library the parameters, unpack the original (bigger) file to memory, close the library and go on to play - only using the Alsa library.

The old flac api could not be used the way I described.

So I am wondering, why you are doing this nice job to bring the morituri-project to the future (I think it is something for perfectionists) and why you go these steps back? There are good reasons, why neither EAC nor moritury forces the users to use flac. May be, even If you could not follow my thoughts, you could give an advice at what places in your code flac could be bypassed.

**Comment by MerlijnWajer** [comment]
FLAC is provably lossless. You can easily write a script to turn those files back into wave files if you so desire.

**Comment by MerlijnWajer** [comment]
Feel free to reopen if you have further comments/questions.
