### ISSUE TITLE
whipper fails to build on bash-compgen

### ISSUE THREAD

**Issue by RecursiveForest** [JoeLametta/whipper#25]
make[2]: Entering directory '/home/samantha/prj/whipper-build/etc/bash_completion.d'
    PYTHONPATH=../..:$PYTHONPATH ./bash-compgen \
        rip morituri.rip.main.Rip > rip
      File "./bash-compgen", line 178
        exec command
                   ^
    SyntaxError: Missing parentheses in call to 'exec'`

I have run through the `git submodule init`, `git submodule update` `./autogen.sh` and `./configure` as specified in the README.

**Comment by RecursiveForest** [comment]
It seems as if all that autogen crap isn't sufficient to figure out whether my system is using python2 or python3 as python, so you have to force PYTHON=$(which python2) (pulled this from the AUR PKGBUILD). I'll be updating the README.

**Comment by RecursiveForest** [comment]
https://github.com/RecursiveForest/whipper/commit/4617fe189373ace9965e612bd729365d1edf9c16 has a fix

**Comment by RecursiveForest** [comment]
[0001-update-README-to-force-python2.txt](https://github.com/JoeLametta/whipper/files/379413/0001-update-README-to-force-python2.txt)

Github is a bit retarded and I can't do two critical things:
1) Fork this repository, since my 'morituri' repo is part of the same 'family'
2) Upload a .patch I have created with `git format-patch`. So I had to change the extension to .txt for you; just change it back and run `git am` on it.

If anyone can tell me how to register my second repo (whipper) as part of this family of repos, please let me know.

**Comment by JoeLametta** [comment]
Merged.
I don't have an answer to your question but I've just added you as collaborator so, if you confirm, you'll get push access to this repository (this way, instead of forking, you can create and work on branches).
