### ISSUE TITLE
New subcommand whipper setup

### ISSUE THREAD

**Issue by waweic** [JoeLametta/whipper#254]
What do you think of a subcommand like `whipper setup` to combine ` whipper drive analyze` and `whipper offset find`? That would make the setup procedure a lot easier for beginners and would also be easier to remember.

**Comment by 45054** [comment]
Good idea but we should rather focus on refactoring the syntax altogether as described in https://github.com/JoeLametta/whipper/issues/21#issuecomment-225448572

**Comment by waweic** [comment]
That seems right, we should focus on that. Closing this now.
