### ISSUE TITLE
Simple message while reading TOC

### ISSUE THREAD

**Issue by Q3CPMA** [JoeLametta/whipper#257]
Hello,
as I already stated in some mash-up issue earlier, when whipper starts reading the TOC, it may seems frozen/stuck to profanes, so some message would be quite helpful. Here's some patch I made (bear with it, I don't know Python) that should get the idea across:
```
diff --git a/whipper/command/cd.py b/whipper/command/cd.py
index e467540..8aaea48 100644
--- a/whipper/command/cd.py
+++ b/whipper/command/cd.py
@@ -98,6 +98,7 @@ class _CD(BaseCommand):
         utils.unmount_device(self.device)

         # first, read the normal TOC, which is fast
+        sys.stdout.write("Reading TOC...")
         self.ittoc = self.program.getFastToc(self.runner, self.device)

         # already show us some info based on this
```

**Comment by RecursiveForest** [comment]
I've created a pull request for the other developers to sign off on at https://github.com/JoeLametta/whipper/pull/258 ; this looks good to me, thanks for submitting a patch!
