### ISSUE TITLE
Make .cue and .m3u writing optional

### ISSUE THREAD

**Issue by ghost** [JoeLametta/whipper#259]
Hello, title says it all, I just delete those and keep the log after ripping.

**Comment by JoeLametta** [comment]
Sorry to say this but: isn't it easier to just delete those files? (as those have an irrelevant size anyway).

**Comment by Q3CPMA** [comment]
Well, it's not hard to do so, but I'm just wondering what's their use when you
rip CDs with one file per track and use a format with gapless playback support.

**Comment by MerlijnWajer** [comment]
The idea is that you can use the cue file to restore the CD in its original form - e.g. you can use it burn an exact copy. At least, that is the idea.

**Comment by Q3CPMA** [comment]
Isn't a TOC file better for this? Anyway, I can understand the cue, but the m3u
always left me quite confused.

**Comment by JoeLametta** [comment]
> Isn't a TOC file better for this?

Well, I think the cue solution has a wider adoption.... There's also a relevant FR: #214.

> the m3u always left me quite confused.

It's just a text file which describes a playlist. For more information just check the [M3U wikipedia page](https://en.wikipedia.org/wiki/M3U).
