### ISSUE TITLE
TypeError on whipper offset find

### ISSUE THREAD

**Issue by Phaaxood** [JoeLametta/whipper#263]
If the calculation of a checksum fails in `program/arc.py`, `accuraterip_checksum` can return `None`. `command/offset.py`'s `Find._arcs` fails in this case with a TypeError when trying to format the `None` as a number in its return value.

(For context: `accuraterip_checksum` fails in my case due to an `illegal hardware instruction` and dumping core when trying to compute a v2 checksum. Thus the `returncode` is nonzero and you might want to die with the `TypeError` and not treat this as a bug.)

**Comment by JoeLametta** [comment]
Thanks for the bug report!

> (For context: accuraterip_checksum fails in my case due to an illegal hardware instruction and dumping core when trying to compute a v2 checksum.

That's quite strange: could you provide a sample file file which shows this behaviour?

Cheers,
Joe

**Comment by Phaaxood** [comment]
The problem is in my laptop being an old 32bit one and accuraterip_checksum not using the right data types for the operations there. See leo-bogert/accuraterip-checksum#2.

**Comment by JoeLametta** [comment]
> The problem is in my laptop being an old 32bit one and accuraterip_checksum not using the right data types for the operations there. See leo-bogert/accuraterip-checksum#2.

Did you install `accuraterip-checksum` from the source code provided in whipper's repository? I'm asking this because the version shipped in this repository has @MerlijnWajer's fixes:

> I've submitted your code for inclusion in whipper/morituri - JoeLametta/whipper#37 with my fixes. Hope that's OK (I think the license matches)

**Comment by Phaaxood** [comment]
No, and I just see that the arch package uses the correct sources, but doesn't build accuraterip-checksum. It just uses the packaged version of it, which comes from leo-bogert's repo. I'll file a bug report there.

So for here it boils down to whether the Exception that might result from `accurateip_checksum` returning `None` is considered a bug or not.

**Comment by JoeLametta** [comment]
> No, and I just see that the arch package uses the correct sources, but doesn't build accuraterip-checksum. It just uses the packaged version of it, which comes from leo-bogert's repo. I'll file a bug report there.

It seems the package in Arch Linux's community repository was marked as `x86_64` only in 2017-11-15: commit [08f26c6](https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/accuraterip-checksum&id=08f26c6219cd2a0cfcdde2bf83756d3ba422718f).
Anyway it seems there's no bug report filed against that package.

> So for here it boils down to whether the Exception that might result from accurateip_checksum returning None is considered a bug or not.

Uhm, if that step fails I think it's better to leave it failing hard (Exception) as I don't see a sensible recovery solution anyway...

**Comment by leo-bogert** [comment]
The most recent code of accuraterip-checksum at https://github.com/leo-bogert/accuraterip-checksum is fixed to work on 32 bit platforms.
Sorry for the inconvenience!

**Comment by mtdcr** [comment]
Please note that PR #274 would remove the dependency on an installed executable by converting accuraterip-checksum to a Python module.
