### ISSUE TITLE
pre emphasis documentation

### ISSUE THREAD

**Issue by sp31415t1** [JoeLametta/whipper#275]
README.md
> Supports reading the pre-emphasis flag embedded into some CDs (and correctly tags the resulting rip)

Is it TOC + subcode or only TOC ?

Is it possible to improve the feature description ?

**Comment by RecursiveForest** [comment]
Right now just TOC. I have a half-finished investigation into how to consistently read the subcode tracks but haven't taken a look at it in some months.

**Comment by JoeLametta** [comment]
> Is it TOC + subcode or only TOC ?

In whipper Just the TOC. `cdrdao` actually reads both: in case those two report conflicting information it issues some warnings (it writes in the tocfile the values taken from the TOC):

```C++
// Check track against TOC control nibbles
ctlCheckOk = 1;
if ((trackCtl & 0x01) !=  (cdToc[i].adrCtl & 0x01)) {
    log_message(-1, "Pre-emphasis flag of track differs from TOC - toc file contains TOC setting.");
    ctlCheckOk = 0;
}
if ((trackCtl & 0x08) != (cdToc[i].adrCtl & 0x08)) {
    log_message(-1, "2-/4-channel-audio  flag of track differs from TOC - toc file contains TOC setting.");
    ctlCheckOk = 0;
}

if (ctlCheckOk) {
    log_message(2, "Control nibbles of track match CD-TOC settings.");
}
```

So, do we want to report those two flags as separate values? (TOC pre-emphasis, subcode pre-emphasis). If that's true, we _just_ need to:

1. Keep note of the track numbers for which cdrdao has emitted the following message: `"Pre-emphasis flag of track differs from TOC - toc file contains TOC setting." (if any)`.
2. For each of the tracks in cdrdao's tocfile read the the pre-emphasis value.
3. If the read value is relative to a track number we kept note before, complement it; else just copy it as is.

**Comment by RecursiveForest** [comment]
I don't think cdrdao can read the subcode on all machines, I believe it's a drive-dependent feature.

**Comment by RecursiveForest** [comment]
But yes, we want to keep track of whether the flag was set in the TOC and/or subcode.
