### ISSUE TITLE
On Arch Linux, CDDB does not know how to install morituri.

### ISSUE THREAD

**Issue by BoBeR182** [JoeLametta/whipper#28]
Checking device /dev/sr0
CDDB disc id: 84081a0c                        
MusicBrainz disc id VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+155706+150+2956+15144+25747+40355+61695+77412+87641+106201+112959+123863+136355&tracks=12&id=VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
Disc duration: 00:34:34.080, 12 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

Could not import python module 'CDDB'
This module is part of python-CDDB.
See http://cddb-py.sourceforge.net/ for more information.

On Arch Linux, CDDB does not know how to install morituri.
    Please file a bug at:
    http://thomas.apestaart.org/morituri/trac/newticket?summary=DEP%3A%20CDDB%2C%20Arch%20Linux
    with instructions on how to install the dependency so we can add it.
    
Please install CDDB and try again.

You can confirm it is installed by starting Python and running:
import CDDB

**Comment by JoeLametta** [comment]
Thanks for reporting this issue. This one isn't new.
It can be fixed but, right now, it isn't the best thing to do because, in the future, whipper is going to abandon python-deps (see #5) which causes this bug.

I'm keeping this issue open as reminder.

**Comment by JoeLametta** [comment]
@BoBeR182 As python-deps has already been dropped can you test if now it works correctly?

Thanks

**Comment by BoBeR182** [comment]
Checking device /dev/sr0
CDDB disc id: 84081a0c                        
MusicBrainz disc id VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+155706+150+2956+15144+25747+40355+61695+77412+87641+106201+112959+123863+136355&tracks=12&id=VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
Disc duration: 00:34:34.080, 12 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

Traceback (most recent call last):
  File "/usr/sbin/rip", line 37, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 45, in main
    h.handleImportError(e)
NameError: global name 'h' is not defined

**Comment by JoeLametta** [comment]
@BoBeR182 Updated again: fixed some `python-deps` leftovers, try it again please.
Now, if I did it right, I expect it to raise an exception because of unmet dependencies.

**Comment by BoBeR182** [comment]
Using configured read offset 6
Checking device /dev/sr0
CDDB disc id: 84081a0c                        
MusicBrainz disc id VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+155706+150+2956+15144+25747+40355+61695+77412+87641+106201+112959+123863+136355&tracks=12&id=VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
Disc duration: 00:34:34.080, 12 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

Traceback (most recent call last):
  File "/usr/sbin/rip", line 38, in <module>
    raise ImportError(e)
ImportError: No module named CDDB

**Comment by BoBeR182** [comment]
Fixed by installing py-cddb
```bash
Using configured read offset 6
Checking device /dev/sr0
CDDB disc id: 84081a0c                        
MusicBrainz disc id VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+155706+150+2956+15144+25747+40355+61695+77412+87641+106201+112959+123863+136355&tracks=12&id=VJ3Z4dFI8V3VWPBbiV9J0g0xqjk-
Disc duration: 00:34:34.080, 12 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as The Knockouts / Main Attraction

**Comment by JoeLametta** [comment]
> Fixed by installing py-cddb

Great!
Yes, that package is required (mentioned in whipper's README as `python-cddb` but, as you've written, it's named `cddb-py` in Arch Linux).

I'll check if `cddb-py` is a strict requirement: in that case I'll ask @neitsab if he can update his AUR`whipper-git` package to mark it as a dependency (not optional anymore).

@BoBeR182 Do you consider this issue to be solved now? (can it be closed?)

**Comment by BoBeR182** [comment]
Yup
