### ISSUE TITLE
Add replaygain processing

### ISSUE THREAD

**Issue by xmixahlx** [JoeLametta/whipper#285]
Request to add replaygain processing by default and/or option.  Processing should be at the end of the successful rip to capture album replaygain values. (If you process replaygain with each track flac encode, then it will only save track values, so we can't just add to the flac encoder settings.)

Example: metaflac --preserve-modtime --add-replay-gain *.flac

**Comment by JoeLametta** [comment]
Hi, this feature would probably be out of scope for whipper's mission. Anyway this ticket seems to be a subset of #244: if interested please keep discussing there.
