### ISSUE TITLE
rip cd info seems to fail

### ISSUE THREAD

**Issue by PlasmaSheep** [JoeLametta/whipper#3]
https://what.cd/forums.php?action=viewthread&threadid=163034&postid=5702764#post5702764

**Comment by JoeLametta** [comment]
Below I'm including, available to the public, the temporary ugly fix which solves this bug:

```diff
--- cd.py
+++ cd_fix.py
@@ -113,11 +113,19 @@
                     self.program.ejectDevice(self.device)
                 return -1
 
-        # now, read the complete index table, which is slower
+        # Ugly fix for broken commit
+        offset = 0
+        info = drive.getDeviceInfo(self.parentCommand.options.device)
+        if info:
+            try:
+                offset = self.getRootCommand().config.getReadOffset(*info)
+            except KeyError:
+                pass
 
+        # now, read the complete index table, which is slower
         self.itable = self.program.getTable(self.runner,
             self.ittoc.getCDDBDiscId(),
-            self.ittoc.getMusicBrainzDiscId(), self.device, self.options.offset)
+            self.ittoc.getMusicBrainzDiscId(), self.device, offset)
 
         assert self.itable.getCDDBDiscId() == self.ittoc.getCDDBDiscId(), \
             "full table's id %s differs from toc id %s" % (
```

**Comment by PlasmaSheep** [comment]
So what's actually wrong with this fix? What would be a better way to do it?

**Comment by JoeLametta** [comment]
It feels "hackish": it doesn't follow the structure of the other code.

**Comment by PlasmaSheep** [comment]
Could you be more specific? :P

How should this be implemented correctly?

**Comment by JoeLametta** [comment]
@PlasmaSheep My "solution" is just a slightly edited copy & paste from the Rip class of the same file.
I'm not sure about it but maybe a better solution would be to implement it through the consolidated `addOptions` and `handleOptions` functions.
In the meantine I've committed the ugly fix to the master branch.

What's your opinion about this?

**Comment by PlasmaSheep** [comment]
You're more familiar with the code base I think, so if there's a nicer way to do it we can do that/

For now the ugly fix will serve, I think.
