### ISSUE TITLE
Disable eject button when ripping

### ISSUE THREAD

**Issue by jtl999** [JoeLametta/whipper#308]
Might be a useful feature to disable the drives eject button when possible, when whipper is running.

It's possible to do so with `eject -i on|off $DEVICE` where on disables the eject button, and off enables it.

**Comment by MerlijnWajer** [comment]
This might be confusing to people who want to actually abort a rip by pressing the physical button, though...

**Comment by jtl999** [comment]
Fair enough, make it optional like EAC then.

**Comment by JoeLametta** [comment]
Hi, what's the use case for this feature?

**Comment by jtl999** [comment]
Sigh. I was just annoyed when I was cleaning my office and I accidentally bumped the eject button on the drive on my desk when it was ripping a scratched disc, so it was taking much longer then normal.

I've already implemented this in the script I use to call whipper for ripping. If someone else wants this implemented natively in whipper, it's not hard to do.
