### ISSUE TITLE
Offset not saved: could not get device info (requires pycdio)

### ISSUE THREAD

**Issue by rootsandculture** [JoeLametta/whipper#33]
Hi, can you please give me instruction to make pycdio work?

Thanks in advance.

**Comment by JoeLametta** [comment]
Hi,

Answered here: [LINK](https://github.com/thomasvs/morituri/issues/155#issuecomment-245332880).

Please tell me if it works for you.

**Comment by rootsandculture** [comment]
It works. Thanks a lot!

**Comment by JoeLametta** [comment]
Glad it helped.
