### ISSUE TITLE
rip offset find seems to fail

### ISSUE THREAD

**Issue by PlasmaSheep** [JoeLametta/whipper#4]
https://what.cd/forums.php?action=viewthread&threadid=163034&postid=5702764#post5702764

**Comment by JoeLametta** [comment]
This one was fixed with the following commit: JoeLametta/whipper@1d046c60f758b5a32e6ba8ac3126e915564f873c
I'm keeping this one open because the solution can be hopefully improved

**Comment by PlasmaSheep** [comment]
What's wrong with this solution?

**Comment by JoeLametta** [comment]
I'm closing this one: the fix is ok but, in the long term, the `offset.py` code should be restructured in a way that takes advantage of the overreading feature currently available (of course this is very low priority).
