### ISSUE TITLE
Error launching rip cd rip command

### ISSUE THREAD

**Issue by rootsandculture** [JoeLametta/whipper#41]
I installed latest eOS (Loki) based on Xenial and I get this error in a fresh whipper installation:

http://pastebin.com/JzcGbFaf

**Comment by JoeLametta** [comment]
I'm not sure but the error is probably related to [this one](https://github.com/thomasvs/morituri/issues/123#issuecomment-178857101). If that's true, please follow the instructions included [here](https://github.com/thomasvs/morituri/issues/123#issuecomment-181000248) and see if that solves it for you.

**Comment by rootsandculture** [comment]
I followed that instructions but doesn't work.

**Comment by rootsandculture** [comment]
Seems to be a libcdio related problem. I tested in a fresh Xubuntu 16.04 install and BEFORE installing libcdio it worked.
I followed this instructions: 

> https://github.com/thomasvs/morituri/issues/123#issuecomment-178857101

And error appears again.

**Comment by JoeLametta** [comment]
> Seems to be a libcdio related problem. I tested in a fresh Xubuntu 16.04 install and BEFORE installing libcdio it worked.

So you didn't build whipper following the instructions provided [here](https://what.cd/forums.php?action=viewthread&threadid=163034&postid=5842960#post5842960), am I right?

**Comment by JoeLametta** [comment]
Closed for lack of updates.
Following the correct install instructions the issue should not arise: not directly related to whipper.
