### ISSUE TITLE
whatlogger no longer recognized

### ISSUE THREAD

**Issue by peaveyman** [JoeLametta/whipper#56]
I just updated whipper a few days ago. I installed whatlogger using the instructions from the readme file. I have whatlogger set as the default logger in the conf file for whipper but when trying to rip a cd it tells me no logger named what found. Could this be because of the backward incompatible changes that were made? Using the whatlogger is essential if whipper is going to be adopted by what.cd as an approved ripper.

**Comment by JoeLametta** [comment]
The AUR package was updated to mention the non backward compatible changes: please read it [HERE](https://aur.archlinux.org/cgit/aur.git/tree/whipper-git.install?h=whipper-git).
As written on What, [morituri-whatlogger](https://github.com/RecursiveForest/morituri-whatlogger)'s README needs to be updated to provide working installation instructions for whipper.

**Comment by RecursiveForest** [comment]
This was a bug with https://github.com/RecursiveForest/morituri-whatlogger which has now been fixed.

**Comment by peaveyman** [comment]
I don't know where those instructions put the plugin but it's not where it's recognized by whipper.

**Comment by JoeLametta** [comment]
@peaveyman

You're right: instructions are wrong. "Build it" section is fine, then do the following:

```
XDG_DATA_HOME=$HOME/.local/share
mkdir -p $XDG_DATA_HOME/.whipper/plugins
cp dist/morituri_*egg $XDG_DATA_HOME/.whipper/plugins
```

Now it should be correctly recognized.

Thanks for the issue report.

**Comment by peaveyman** [comment]
Nope, still doesn't recognize the plugin.

**Comment by JoeLametta** [comment]
There was a bug in whipper's code: try updating it and please test if the logger plugin gets recognized (there should be no need to follow the instructions from the start again).

Just try running:  `rip cd rip --help`

**Comment by peaveyman** [comment]
I just now updated whipper. The logger plugin isn't recognized. Following this instructions here:

https://github.com/RecursiveForest/morituri-whatlogger
After the plugin installation the instructions to cp the plugin to the proper folder doesn't work. 
This is what I ran: export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"${HOME}/.config"}
mkdir -p $XDG_CONFIG_HOME/.whipper/plugins
cp dist/morituri_*egg $XDG_CONFIG_HOME/.whipper/plugins

I don't know where XDG_CONFIG_HOME is. I thought it would be like this: /home/gary/.whipper/plugins but after running this I still don't have /home/gary/.whipper/plugins. I have /home/gary/.whipper but I had already created that folder earlier.

**Comment by JoeLametta** [comment]
> I just now updated whipper. The logger plugin isn't recognized.

1. First of all please confirm the version of whipper you're using running: `rip -v`.
2. Then issue the following commands (deleting unneeded paths):

    ````bash
    rm -rf "$HOME/.whipper"
    rm -rf "$HOME/.config/.whipper/plugins"
    rm -rf "$HOME/.local/share/.whipper"
    ````

3. Follow the fixed instructions reported below:

---

To use this plugin:

* build it:

  ````bash
  git clone https://github.com/RecursiveForest/morituri-whatlogger.git
  cd morituri-whatlogger
  python2 setup.py bdist_egg
  ````

* copy it to your plugin directory:

  ````bash
  export XDG_DATA_HOME=${XDG_DATA_HOME:-"${HOME}/.local/share"}
  mkdir -p $XDG_DATA_HOME/.whipper/plugins
  cp dist/morituri_*egg $XDG_DATA_HOME/.whipper/plugins
  ````

* verify that it gets recognized:

  ````bash
  rip cd rip --help
  ````

  You should see 'what' as a possible logger.

* use it:

  ````bash
  rip cd rip -L what
  ````

**Comment by peaveyman** [comment]
This still isn't putting the logger plugin where it needs to be, which is ~/.local/share/whipper/plugins

**Comment by peaveyman** [comment]
It seems the problem, for me at least, is this:

mkdir -p $XDG_DATA_HOME/.whipper/plugins
cp dist/morituri_*egg $XDG_DATA_HOME/.whipper/plugins

Need to change .whipper to whipper

**Comment by JoeLametta** [comment]
You're right: didn't spot the erroneous dot at night (sorry). I've updated the instructions in my previous message.

BTW: You can find all correct paths whipper uses in the [README](https://github.com/JoeLametta/whipper/tree/master#backward-incompatible-changes).

**Comment by RecursiveForest** [comment]
This is a bug with the logger('s readme), you should file such bugs over at the correct repository so I get properly notified about them.

However, the latest git head has this fixed, thanks.

**Comment by peaveyman** [comment]
Sorry about that. I wasn't thinking. Thanks for the heads up about it.
