### ISSUE TITLE
Remove connection to parent fork.

### ISSUE THREAD

**Issue by BoBeR182** [JoeLametta/whipper#79]
Seeing as https://github.com/thomasvs/morituri has become abandonware and we have started using the command `whipper` instead of `rip`, I move that we ask github to defork our project from the parent and be our own root repo.

**Comment by JoeLametta** [comment]
This should be OK (README and project description both mention that whipper was forked from morituri): my only worry is that this move could harm whipper's discoverability.

Before proceeding let's hear what other people think about this one...

**Comment by BoBeR182** [comment]
This move will actually increase Whippers discoverability as you will be able to use Github's index to search the code, and it's google rank will increase.

**Comment by RecursiveForest** [comment]
+1 to deforking, although I don't understand how this affects the google rank / GH index. (Due to lack of knowledge, not a disagreement.)

**Comment by MerlijnWajer** [comment]
I would leave it like this for now, but I don't care too much. Unless it really hurts the discoverability.

You could ask Thomas to link to the project/fork, if you do want to 'unfork'?

Maybe we should really get version 1.0 out first

**Comment by JoeLametta** [comment]
> You could ask Thomas to link to the project/fork, if you do want to 'unfork'?

I'll ask him.

> Maybe we should really get version 1.0 out first

Exactly.
Then we'll decide how to proceed (unfork is probable).

**Comment by BoBeR182** [comment]
![firefox_screenshot_2016-11-30t14-38-40 676z](https://cloud.githubusercontent.com/assets/525433/20756487/da4ef5fc-b6e0-11e6-9c32-8c230f7e8b2e.png)
We currently are not even on page 1, because we are a fork.

**Comment by tobbez** [comment]
I'd be careful with jumping to conclusions. There doesn't seem to be any public documentation confirming that fork status affects search rankings, which means this is just guessing.

I'd argue that it doesn't really matter that whipper is displayed as a fork. In fact, it makes it easier for people to find it (via the network graph, for example), and more easily realize that whipper is the more active project ("This branch is X commits ahead of thomasvs:master").

I also remember seeing many other projects where the main development effort has moved from the "original upstream" to a fork, which has become the new "real" project (while still being displayed as a fork).

The only thing I can see that is affected is GitHub's own search (which doesn't include forks by default), but I don't think GitHub drives a lot of search traffic (compared to Google, where whipper is already the first result for "whipper ripper")

**Comment by JoeLametta** [comment]
> You could ask Thomas to link to the project/fork, if you do want to 'unfork'?
>> 
>> I'll ask him.

Just wanted to let you know that it seems Thomas doesn't want to link to whipper in morituri's README.

@tobbez
That's a good point, thanks.

Please let's all discuss in order to reach a consensus about the best way to proceed.

**Comment by ArchangeGabriel** [comment]
Did you actually got an answer from him? I’ve tried to reach him twice some time ago about morituri, but never got an answer.

**Comment by JoeLametta** [comment]
> Did you actually got an answer from him? I’ve tried to reach him twice some time ago about morituri, but never got an answer.

Yep, here it is (2016/12/03):

---

> What makes you think it is unmaintained?
> 
> On Dec 3, 2016, JoeLametta wrote:
> 
>> Hi Thomas,
>> I'm JoeLametta (author of the whipper morituri fork): as morituri seems to be unmaintained, I wanted to ask if you could link / mention whipper into morituri's README.
>> 
>> Thanks in advance.
>> 
>> Cheers,
>> Joe

---

I then replied to his message with the following one which still didn't get any reply (2016/12/04):

---

> "Latest commit 135b2f7 on 10 Nov 2015".
> There's also a certain number of pull requests which have been there without a comment for a long time; issues reported without  a single reply from the project maintainer, etc.
> 
> If I'm wrong, I'd like to have an official clarification about morituri's project status.
> 
> Thanks in advance.
> 
> Cheers,
> Joe

**Comment by ArchangeGabriel** [comment]
OK, here is my own email to him on 2016/03/28:

> Hi Thomas,
> 
> First of all, I would like to thank you very much for all the great work
> you’ve done so far on this project. :) morituri has always allowed me to
> rip my CD correctly, while using MusicBrainz for tags, a great combo. ;)
> 
> However, the project seems to be dying. :( You haven’t been comitting
> code or answering issues for quite some time now, and the code is
> getting deprecated. Indeed, gstreamer0.10 is leaving main distros (not
> in debian anymore as of 9.x), making morituri unable to work on such
> platforms. Also, they are some issues/features requiring attention…
> 
> I understand that you might be busy elsewhere, or even have not interest
> anymore in morituri. But either way, could you please issue a statement
> regarding the future of morituri, your involvement in it, or steps to
> accomplish and how to get into them for potential other contributors?
> 
> morituri is quite a great tool, it would be a shame that it dies like
> this. ;)
> 
> Hope to hear from you soon,
> Bruno

Never received any answer.

**Comment by Freso** [comment]
I don't think whipper is going to be turned back into morituri at this point. It's gotten its own life now. Also, with #109 the codebase only mentions morituri for historical purposes. I think it'd be fine to "disconnect" the repository now.

**Comment by JoeLametta** [comment]
> I think it'd be fine to "disconnect" the repository now.

What about @tobbez point then?

**Comment by tobbez** [comment]
For the record, I don't have strong opinion either way at this point.

If you do the disconnect, it would be apt to change the first sentence of the README to read something like `Whipper is a Python 2 CD-DA ripper, originally based on the morituri project [...]` as well, rather than the current (`Whipper is a Python 2 CD-DA ripper, fork of the morituri project`).

**Comment by MerlijnWajer** [comment]
Let's remove the fork connection on github, but keep it in the README. I think that should be fine.

**Comment by RecursiveForest** [comment]
+1 to removing the fork on github

**Comment by JoeLametta** [comment]
I've just contacted GitHub to ask if they can unfork whipper from morituri.

**Comment by JoeLametta** [comment]
Thanks to GitHub's staff now whipper has been unlinked from morituri.

:fireworks:

**Comment by Freso** [comment]
Note that the project description here in GH still says «Python CD-DA ripper preferring accuracy over speed (FORKED from morituri)». There should be an "Edit" button at https://github.com/JoeLametta/whipper/ that'll allow you to edit this.

**Comment by JoeLametta** [comment]
> Note that the project description here in GH still says «Python CD-DA ripper preferring accuracy over speed (FORKED from morituri)»

Good catch, thanks. I've just removed the "(FORKED from morituri)" part.
